try:
    print(x)
except AssertionError  as error:
    print(error)